name: re_highlight
description: Re-Highlight is a powerful text syntax highlighting library.
version: 0.0.3
homepage: https://reqable.com
repository: https://github.com/reqable/re-highlight

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies: 
  dart_code_metrics:
    git: https://github.com/JonasWanke/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0